=== GIM-be/core-geonetwork/schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/labels/schema-labels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2001-2016 Food and Agriculture Organization of the
  ~ United Nations (FAO-UN), United Nations World Food Programme (WFP)
  ~ and United Nations Environment Programme (UNEP)
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or (at
  ~ your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
  ~
  ~ Contact: Jeroen Ticheler - FAO - Viale delle Terme di Caracalla 2,
  ~ Rome - Italy. email: geonetwork@osgeo.org
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:element name="labels">
    <xs:annotation>
      <xs:documentation>A list of labels describing standard descriptors
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="element">
          <xs:annotation>
            <xs:documentation>A descriptor with label, definition, help text and
              suggestions
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="element">
    <xs:complexType>
      <xs:all>
        <xs:element ref="label" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>The descriptor label to display next
              to the field
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="description" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>The definition to be displayed in the help
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="help" minOccurs="0">
          <xs:annotation>
            <xs:documentation>More help (CDATA could be used to store HTML)
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="condition" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>CHECKME: Not really used ?</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="example" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>Examples to be added to the help section
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="helper" minOccurs="0">
          <xs:annotation>
            <xs:documentation>List of suggestion to be displayed in edit mode to
              help populating the field. It's ussually common values for a
              field.
              More than one helper could be define if needed to match different
              scope of metadata (eg. metadata on dataset and metadata on
              service).
              In that case, a displayIf attribute is added to define when to
              display that helper list.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="mandatoryType" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>In case the condition element is set to mandatory,
              this element will determine the mandatory type.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="mandatoryTooltip" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>Tooltip displayed when hovering the mandatory indicator</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:all>
      <xs:attribute name="context" type="xs:NMTOKEN">
        <xs:annotation>
          <xs:documentation>Parent element name or full XPath</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="id" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>An optional reference to the standard descriptor
            identifier.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="condition" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="help" type="xs:string"/>
  <xs:element name="label" type="xs:string"/>
  <xs:element name="example" type="xs:string"/>
  <xs:element name="mandatoryType" type="xs:string"/>
  <xs:element name="mandatoryTooltip" type="xs:string"/>

  <xs:element name="helper">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="option">
          <xs:annotation>
            <xs:documentation>Suggestion is an HTML option</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="rel" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of the element to be populated by the title
            attribute of the option. That parameter allows to update 2 fields in
            the editor at a time.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="relAtt" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of an attribute (eg. uom) to be populated by
            the title attribute of the option. That parameter allows to update 2
            fields in the editor at a time.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="sort" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Set this attribute to true to sort by alpha order.
            By default, the helpers are displayed in the order define in labels
            file.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="editorMode">
        <xs:annotation>
          <xs:documentation>By default, the list of suggestion is displayed in a
            combo next to the
            element. The layout may be customized by setting the editorMode.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="radio">
              <xs:annotation>
                <xs:documentation>Simple radio displayed next to each other.
                </xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="radio_withdesc">
              <xs:annotation>
                <xs:documentation>Radio button with label and the description
                  define in the title attribute.
                </xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="radio_linebreak">
              <xs:annotation>
                <xs:documentation>Radio button with line break between each of
                  them (maybe better to use CSS to define this).
                </xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="displayIf" type="xs:string">
        <xs:annotation>
          <xs:documentation>
            <![CDATA[
          Conditional helpers which may define an xpath expression to evaluate if the xpath match.

        The scope of the expression is defined by a variable named "$p1" whitch is the current node.

        For example, to match a metadata on dataset:
        displayIf="$p1/ancestor::node()[name()='gmd:MD_Metadata']/gmd:identificationInfo/gmd:MD_DataIdentification or
        $p1/ancestor::node()[name()='gmd:MD_Metadata']/gmd:identificationInfo/*[@gco:isoType='gmd:MD_DataIdentification']"

        and a metadata on service:
        displayIf="$p1/ancestor::node()[name()='gmd:MD_Metadata']/gmd:identificationInfo/srv:SV_ServiceIdentification"

          ]]>
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="option">
    <xs:complexType mixed="true">
      <xs:attribute name="id" type="xs:NMTOKEN"/>
      <xs:attribute name="title"/>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="inspireInfo" type="xs:string"/>

  <xs:element name="codelists">
    <xs:annotation>
      <xs:documentation>* Hide in edit mode : If some codelist needs to be
        hidden
        in edit mode, the hideInEditMode attribute could be added
        to any entries.

        eg.
        &lt;entry hideInEditMode="true">

        This will restrict the number of available entries for end
        user editors and keep all records ISO compatible when using
        codelist (eg. harvested records could use codelist hidden
        in local node and needs to be displayed in view mode).

        By default, this attribute is not used.

        * editorMode attribute allows to configure the editor form field.

        * - not set -: simple combo box
        * radio : radio button in one line
        * radio_linebreak : radio button with line break
        * radio_withdesc : radion button with line break and codelist entry
        description
        * select : select box with size set to the number of items if lower than
        7 entries.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded" minOccurs="0">
        <xs:element name="codelist">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
              <xs:element name="entry">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="code"/>
                    <xs:element type="xs:string" name="label"/>
                    <xs:element type="xs:string" name="description"/>
                  </xs:sequence>
                  <xs:attribute type="xs:boolean" name="hideInEditMode" use="optional"/>
                  <xs:attribute type="xs:boolean" name="default" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute type="xs:string" name="alias" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== GIM-be/core-geonetwork/schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2001-2016 Food and Agriculture Organization of the
  ~ United Nations (FAO-UN), United Nations World Food Programme (WFP)
  ~ and United Nations Environment Programme (UNEP)
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or (at
  ~ your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
  ~
  ~ Contact: Jeroen Ticheler - FAO - Viale delle Terme di Caracalla 2,
  ~ Rome - Italy. email: geonetwork@osgeo.org
  -->

<labels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:gco="http://www.isotc211.org/2005/gco"
        xmlns:gmd="http://www.isotc211.org/2005/gmd"
        xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gml="http://www.opengis.net/gml"
        xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gmx="http://www.isotc211.org/2005/gmx"
        xsi:noNamespaceSchemaLocation="../../../../../../../schema-labels.xsd">

  <element name="gmd:MD_ScopeCode">
    <label>Scope code</label>
    <description>Class of information to which the referencing entity applies</description>
  </element>
  <element name="code" id="207.0" context="gmd:MD_Identifier">
    <label>Code</label>
    <description>Alphanumeric value identifying an instance in the namespace</description>
    <help>alphanumeric value identifying an instance in the namespace</help>
  </element>
  <element name="code">
    <label>System code</label>
    <description>Code. i.e. EPSG code.</description>
  </element>
  <element name="code" id="547.0" context="gmd:MD_CodeValue">
    <label>Code</label>
    <description>Value code</description>
    <help>Value code (i.e. numeric)</help>
  </element>
  <element name="codeSpace" id="208.1">
    <label>Reference Authority</label>
    <description>Authority responsible for codification. i.e. EPSG</description>
  </element>
  <element name="gco:Date" id="364.0" context="gmd:CI_Citation">
    <label>Edition Date</label>
    <description>Date of the edition</description>
  </element>
  <element name="gco:Date" id="393.0">
    <label>Date</label>
    <description>Formatted as 2007-09-12 (YYYY-MM-DD)</description>
    <help>reference date and event used to describe it</help>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gco:DateTime" id="64.0" context="gmd:MD_Usage">
    <description>Formatted as 2007-09-12T15:00:00 (YYYY-MM-DDTHH:mm:ss)</description>
    <label>Usage Date / Time</label>
    <help>date and time of the first use or range of uses of the resource and/or resource
      series
    </help>
  </element>
  <element name="gco:DateTime" id="300.0" context="gmd:MD_StandardOrderProcess">
    <description>Formatted as 2007-09-12T15:00:00 (YYYY-MM-DDTHH:mm:ss)</description>
    <label>Planned Available Date / Time</label>
    <help>date and time when theresource will be available</help>
  </element>
  <element name="gco:DateTime">
    <label>Date and time</label>
    <description>Date and time or range of date and time on or over which the process step occurred
      (YYYY-MM-DDThh:mm:ss)
    </description>
  </element>
  <element name="gco:Measure" id="100.0" context="gmd:DQ_Element">
    <label>Name of Measure</label>
    <description>Name of the test applied to the data</description>
  </element>
  <element name="gco:Measure" id="357.0" context="gmd:EX_VerticalExtent">
    <label>Unit of Measure</label>
    <description>Vertical units used for vertical extent information Examples: metres, feet,
      millimetres, hectopascals
    </description>
    <_condition>M</_condition>
  </element>
  <element name="gmd:CI_Address" id="380.0">
    <label>Address</label>
    <description>Location of the responsible individual or organization</description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:CI_Citation" id="359.0">
    <label>Citation</label>
    <description>Standardised resource reference</description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:CI_Contact" id="387.0">
    <label>Contact</label>
    <description>Information required to enable contact with the responsible person and/or
      organization
    </description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:CI_Date" id="393.0">
    <label>Date</label>
    <description>Reference date and event used to describe it (YYYY-MM-DD)</description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:CI_DateTypeCode">
    <label>Date type code</label>
    <description/>
  </element>
  <element name="gmd:CI_OnLineFunctionCode">
    <label>OnLine function code</label>
    <description/>
  </element>
  <element name="gmd:CI_PresentationFormCode">
    <label>Presentatiewijze code</label>
    <description/>
  </element>
  <element name="gmd:CI_OnlineResource" id="396.0">
    <label>OnLine resource</label>
    <description>Information about on-line sources from which the dataset, specification, or
      community profile name and extended metadata elements can be obtained
    </description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:CI_ResponsibleParty" id="374.0">
    <label>Responsible party</label>
    <description>Identification of, and means of communication with, person(s) and organizations
      associated with the dataset
    </description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:CI_Series" id="403.0">
    <label>Series</label>
    <description>Information about the series, or aggregate dataset, to which a dataset
      belongs
    </description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:CI_Telephone" id="407.0">
    <label>Telephone</label>
    <description>Telephone numbers for contacting the responsible individual or
      organization
    </description>
    <_condition>Use obligation/condition from referencing object</_condition>
  </element>
  <element name="gmd:DQ_AbsoluteExternalPositionalAccuracy" id="117.0">
    <label>Absolute external positional accuracy</label>
    <description>Closeness of reported coordinate values to values accepted as or being
      true
    </description>
  </element>
  <element name="gmd:DQ_AccuracyOfATimeMeasurement" id="121.0">
    <label>Accuracy of time measurement</label>
    <description>Correctness of the temporal references of an item (reporting of error in time
      measurement)
    </description>
  </element>
  <element name="gmd:DQ_CompletenessCommission" id="109.0">
    <label>Completeness commission</label>
    <description>Excess data present in the dataset, as described by the scope</description>
  </element>
  <element name="gmd:DQ_CompletenessOmission" id="110.0">
    <label>Completeness omission</label>
    <description>Data absent from the dataset, as described by the scope</description>
  </element>
  <element name="gmd:DQ_ConceptualConsistency" id="112.0">
    <label>Conceptual consistency</label>
    <description>Adherence to rules of the conceptual schema</description>
  </element>
  <element name="gmd:DQ_ConformanceResult" id="129.0">
    <label>Conformance result</label>
    <description>Information about the outcome of evaluating the obtained value (or set of
      values) against a specified acceptable conformance quality level
    </description>
  </element>
  <element name="gmd:DQ_DataQuality" id="78.0">
    <label>Data quality</label>
    <description>Quality information for the data specified by a data quality
      scope
    </description>
  </element>
  <element name="gmd:DQ_DomainConsistency" id="113.0">
    <label>Domain consistency</label>
    <description>Adherence of values to the value domains</description>
  </element>
  <element name="gmd:DQ_EvaluationMethodTypeCode">
    <label>Evaluation method type code</label>
    <description>type of method for evaluating an identified data quality
      measure
    </description>
  </element>
  <element name="gmd:DQ_FormatConsistency" id="114.0">
    <label>Format consistency</label>
    <description>Degree to which data is stored in accordance with the physical structure of the
      dataset, as described by the scope
    </description>
  </element>
  <element name="gmd:DQ_GriddedDataPositionalAccuracy" id="118.0">
    <label>Gridded data positional accuracy</label>
    <description>Closeness of gridded data position values to values accepted as or being
      true
    </description>
  </element>
  <element name="gmd:DQ_NonQuantitativeAttributeAccuracy" id="126.0">
    <label>Non quantitative attribute accuracy</label>
    <description>Correctness of non-quantitative attributes</description>
  </element>
  <element name="gmd:DQ_QuantitativeAttributeAccuracy" id="127.0">
    <label>Quantitative attribute accuracy</label>
    <description>Accuracy of quantitative attributes</description>
  </element>
  <element name="gmd:DQ_QuantitativeResult" id="133.0">
    <label>Quantitative result</label>
    <description>The values or information about the value(s) (or set of values) obtained from
      applying a data quality measure
